version: '3'
services:
    server:
        build: ./
        environment:
            DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/lireddit
            REDIS_URL: redis://host.docker.internal:6379
            PORT: 4000
            SESSION_SECRET: something
            CORS_ORIGIN: http://host.docker.internal:3000
        ports:
            - 4000:4000
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
    redis:
        image: redis
        ports:
            - 6379:6379
